package kanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static kanta.Apu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.06.26 12:52:50 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class ApuTest {



  // Generated by ComTest BEGIN
  /** testTarkistaPvm30 */
  @Test
  public void testTarkistaPvm30() {    // Apu: 30
    assertEquals("From: Apu line: 31", "kiellettyjä merkkejä", tarkistaPvm("abcdefgh")); 
    assertEquals("From: Apu line: 32", "pvm pitää olla muotoa pp.kk.vv", tarkistaPvm("1.1.2023")); 
    assertEquals("From: Apu line: 33", "liian pieni pvm", tarkistaPvm("00.01.2023")); 
    assertEquals("From: Apu line: 34", "liian pieni pvm", tarkistaPvm("01.00.2023")); 
    assertEquals("From: Apu line: 35", "liian pieni pvm", tarkistaPvm("01.01.1999")); 
    assertEquals("From: Apu line: 36", "liian suuri pvm", tarkistaPvm("32.01.2023")); 
    assertEquals("From: Apu line: 37", "liian suuri pvm", tarkistaPvm("01.13.2023")); 
    assertEquals("From: Apu line: 38", "liian suuri pvm", tarkistaPvm("01.01.2100")); 
    assertEquals("From: Apu line: 39", null, tarkistaPvm("09.06.2023")); 
    assertEquals("From: Apu line: 40", null, tarkistaPvm("10.06.2023")); 
    assertEquals("From: Apu line: 41", null, tarkistaPvm("12.06.2023")); 
  } // Generated by ComTest END
}