package punttisalimuistio.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import punttisalimuistio.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.06.11 20:38:27 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PunttisalimuistioTest {



  // Generated by ComTest BEGIN
  /** 
   * testGetTreeneja40 
   * @throws SailoException when error
   */
  @Test
  public void testGetTreeneja40() throws SailoException {    // Punttisalimuistio: 40
    Punttisalimuistio muistio = new Punttisalimuistio(); 
    Treeni tre1 = new Treeni(); 
    Treeni tre2 = new Treeni(); 
    tre1.rekisteroi(); tre2.rekisteroi(); 
    assertEquals("From: Punttisalimuistio line: 47", 0, muistio.getTreeneja()); 
    muistio.lisaa(tre1); assertEquals("From: Punttisalimuistio line: 48", 1, muistio.getTreeneja()); 
    muistio.lisaa(tre2); assertEquals("From: Punttisalimuistio line: 49", 2, muistio.getTreeneja()); 
    muistio.lisaa(tre1); assertEquals("From: Punttisalimuistio line: 50", 3, muistio.getTreeneja()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaTreeni64 
   * @throws SailoException when error
   */
  @Test
  public void testAnnaTreeni64() throws SailoException {    // Punttisalimuistio: 64
    Punttisalimuistio muistio = new Punttisalimuistio(); 
    Treeni tre1 = new Treeni(); 
    Treeni tre2 = new Treeni(); 
    tre1.rekisteroi(); tre2.rekisteroi(); 
    assertEquals("From: Punttisalimuistio line: 71", 0, muistio.getTreeneja()); 
    muistio.lisaa(tre1); assertEquals("From: Punttisalimuistio line: 72", tre1, muistio.annaTreeni(0)); 
    muistio.lisaa(tre2); assertEquals("From: Punttisalimuistio line: 73", tre2, muistio.annaTreeni(1)); 
    muistio.lisaa(tre1); assertEquals("From: Punttisalimuistio line: 74", tre1, muistio.annaTreeni(2)); 
    try {
    assertEquals("From: Punttisalimuistio line: 75", tre1, muistio.annaTreeni(3)); 
    fail("Punttisalimuistio: 75 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaLiikkeet88 */
  @Test
  public void testAnnaLiikkeet88() {    // Punttisalimuistio: 88
    Punttisalimuistio muistio = new Punttisalimuistio(); 
    Treeni tre1 = new Treeni(), tre2 = new Treeni(), tre3 = new Treeni(); 
    tre1.rekisteroi(); tre2.rekisteroi(); tre3.rekisteroi(); 
    int id1 = tre1.getTunnusNro(); 
    int id2 = tre2.getTunnusNro(); 
    Liike lii11 = new Liike(id1); muistio.lisaa(lii11); 
    Liike lii12 = new Liike(id1); muistio.lisaa(lii12); 
    Liike lii21 = new Liike(id2); muistio.lisaa(lii21); 
    Liike lii22 = new Liike(id2); muistio.lisaa(lii22); 
    Liike lii23 = new Liike(id2); muistio.lisaa(lii23); 
    List<Liike> loytyneet; 
    loytyneet = muistio.annaLiikkeet(tre3); 
    assertEquals("From: Punttisalimuistio line: 103", 0, loytyneet.size()); 
    loytyneet = muistio.annaLiikkeet(tre1); 
    assertEquals("From: Punttisalimuistio line: 105", 2, loytyneet.size()); 
    assertEquals("From: Punttisalimuistio line: 106", true, loytyneet.get(0) == lii11); 
    assertEquals("From: Punttisalimuistio line: 107", true, loytyneet.get(1) == lii12); 
    loytyneet = muistio.annaLiikkeet(tre2); 
    assertEquals("From: Punttisalimuistio line: 109", 3, loytyneet.size()); 
    assertEquals("From: Punttisalimuistio line: 110", true, loytyneet.get(0) == lii21); 
    assertEquals("From: Punttisalimuistio line: 111", true, loytyneet.get(1) == lii22); 
    assertEquals("From: Punttisalimuistio line: 112", true, loytyneet.get(2) == lii23); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa125 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa125() throws SailoException {    // Punttisalimuistio: 125
    Punttisalimuistio muistio = new Punttisalimuistio(); 
    Treeni tre1 = new Treeni(); 
    Treeni tre2 = new Treeni(); 
    tre1.rekisteroi(); tre2.rekisteroi(); 
    assertEquals("From: Punttisalimuistio line: 132", 0, muistio.getTreeneja()); 
    muistio.lisaa(tre1); assertEquals("From: Punttisalimuistio line: 133", 1, muistio.getTreeneja()); 
    muistio.lisaa(tre2); assertEquals("From: Punttisalimuistio line: 134", 2, muistio.getTreeneja()); 
    muistio.lisaa(tre1); assertEquals("From: Punttisalimuistio line: 135", 3, muistio.getTreeneja()); 
    assertEquals("From: Punttisalimuistio line: 137", tre1, muistio.annaTreeni(0)); 
    assertEquals("From: Punttisalimuistio line: 138", tre2, muistio.annaTreeni(1)); 
    assertEquals("From: Punttisalimuistio line: 139", tre1, muistio.annaTreeni(2)); 
    try {
    assertEquals("From: Punttisalimuistio line: 140", tre1, muistio.annaTreeni(3)); 
    fail("Punttisalimuistio: 140 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    muistio.lisaa(tre1); muistio.lisaa(tre2); 
    muistio.lisaa(tre1); muistio.lisaa(tre2); 
    muistio.lisaa(tre1); muistio.lisaa(tre2); 
    muistio.lisaa(tre1); muistio.lisaa(tre2); 
    try {
    muistio.lisaa(tre1); muistio.lisaa(tre2); 
    fail("Punttisalimuistio: 146 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa157 */
  @Test
  public void testLisaa157() {    // Punttisalimuistio: 157
    Punttisalimuistio muistio = new Punttisalimuistio(); 
    Treeni tre1 = new Treeni(), tre2 = new Treeni(), tre3 = new Treeni(); 
    tre1.rekisteroi(); tre2.rekisteroi(); tre3.rekisteroi(); 
    int id1 = tre1.getTunnusNro(); 
    int id2 = tre2.getTunnusNro(); 
    Liike lii11 = new Liike(id1); muistio.lisaa(lii11); 
    Liike lii12 = new Liike(id1); muistio.lisaa(lii12); 
    Liike lii21 = new Liike(id2); muistio.lisaa(lii21); 
    Liike lii22 = new Liike(id2); muistio.lisaa(lii22); 
    Liike lii23 = new Liike(id2); muistio.lisaa(lii23); 
    List<Liike> loytyneet; 
    loytyneet = muistio.annaLiikkeet(tre3); 
    assertEquals("From: Punttisalimuistio line: 172", 0, loytyneet.size()); 
    loytyneet = muistio.annaLiikkeet(tre1); 
    assertEquals("From: Punttisalimuistio line: 174", 2, loytyneet.size()); 
    assertEquals("From: Punttisalimuistio line: 175", true, loytyneet.get(0) == lii11); 
    assertEquals("From: Punttisalimuistio line: 176", true, loytyneet.get(1) == lii12); 
    loytyneet = muistio.annaLiikkeet(tre2); 
    assertEquals("From: Punttisalimuistio line: 178", 3, loytyneet.size()); 
    assertEquals("From: Punttisalimuistio line: 179", true, loytyneet.get(0) == lii21); 
    assertEquals("From: Punttisalimuistio line: 180", true, loytyneet.get(0) == lii21); 
    assertEquals("From: Punttisalimuistio line: 181", true, loytyneet.get(1) == lii22); 
    assertEquals("From: Punttisalimuistio line: 182", true, loytyneet.get(2) == lii23); 
  } // Generated by ComTest END
}