package punttisalimuistio.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import punttisalimuistio.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.06.07 13:27:55 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PunttisalimuistioTest {



  // Generated by ComTest BEGIN
  /** 
   * testGetTreeneja36 
   * @throws SailoException when error
   */
  @Test
  public void testGetTreeneja36() throws SailoException {    // Punttisalimuistio: 36
    Punttisalimuistio muistio = new Punttisalimuistio(); 
    Treeni tre1 = new Treeni(); 
    Treeni tre2 = new Treeni(); 
    tre1.rekisteroi(); tre2.rekisteroi(); 
    assertEquals("From: Punttisalimuistio line: 43", 0, muistio.getTreeneja()); 
    muistio.lisaa(tre1); assertEquals("From: Punttisalimuistio line: 44", 1, muistio.getTreeneja()); 
    muistio.lisaa(tre2); assertEquals("From: Punttisalimuistio line: 45", 2, muistio.getTreeneja()); 
    muistio.lisaa(tre1); assertEquals("From: Punttisalimuistio line: 46", 3, muistio.getTreeneja()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaTreeni60 
   * @throws SailoException when error
   */
  @Test
  public void testAnnaTreeni60() throws SailoException {    // Punttisalimuistio: 60
    Punttisalimuistio muistio = new Punttisalimuistio(); 
    Treeni tre1 = new Treeni(); 
    Treeni tre2 = new Treeni(); 
    tre1.rekisteroi(); tre2.rekisteroi(); 
    assertEquals("From: Punttisalimuistio line: 67", 0, muistio.getTreeneja()); 
    muistio.lisaa(tre1); assertEquals("From: Punttisalimuistio line: 68", tre1, muistio.annaTreeni(0)); 
    muistio.lisaa(tre2); assertEquals("From: Punttisalimuistio line: 69", tre2, muistio.annaTreeni(1)); 
    muistio.lisaa(tre1); assertEquals("From: Punttisalimuistio line: 70", tre1, muistio.annaTreeni(2)); 
    try {
    assertEquals("From: Punttisalimuistio line: 71", tre1, muistio.annaTreeni(3)); 
    fail("Punttisalimuistio: 71 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa84 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa84() throws SailoException {    // Punttisalimuistio: 84
    Punttisalimuistio muistio = new Punttisalimuistio(); 
    Treeni tre1 = new Treeni(); 
    Treeni tre2 = new Treeni(); 
    tre1.rekisteroi(); tre2.rekisteroi(); 
    assertEquals("From: Punttisalimuistio line: 91", 0, muistio.getTreeneja()); 
    muistio.lisaa(tre1); assertEquals("From: Punttisalimuistio line: 92", 1, muistio.getTreeneja()); 
    muistio.lisaa(tre2); assertEquals("From: Punttisalimuistio line: 93", 2, muistio.getTreeneja()); 
    muistio.lisaa(tre1); assertEquals("From: Punttisalimuistio line: 94", 3, muistio.getTreeneja()); 
    assertEquals("From: Punttisalimuistio line: 96", tre1, muistio.annaTreeni(0)); 
    assertEquals("From: Punttisalimuistio line: 97", tre2, muistio.annaTreeni(1)); 
    assertEquals("From: Punttisalimuistio line: 98", tre1, muistio.annaTreeni(2)); 
    try {
    assertEquals("From: Punttisalimuistio line: 99", tre1, muistio.annaTreeni(3)); 
    fail("Punttisalimuistio: 99 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    muistio.lisaa(tre1); muistio.lisaa(tre2); 
    muistio.lisaa(tre1); muistio.lisaa(tre2); 
    muistio.lisaa(tre1); muistio.lisaa(tre2); 
    muistio.lisaa(tre1); muistio.lisaa(tre2); 
    try {
    muistio.lisaa(tre1); muistio.lisaa(tre2); 
    fail("Punttisalimuistio: 105 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}