package punttisalimuistio.test;
// Generated by ComTest BEGIN
import java.io.File;
import punttisalimuistio.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.06.26 12:55:08 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TreenitTest {



  // Generated by ComTest BEGIN
  /** testLisaa49 */
  @Test
  public void testLisaa49() {    // Treenit: 49
    Treenit treenit = new Treenit(); 
    Treeni tre1 = new Treeni(); 
    Treeni tre2 = new Treeni(); 
    assertEquals("From: Treenit line: 53", 0, treenit.getLkm()); 
    treenit.lisaa(tre1); assertEquals("From: Treenit line: 54", 1, treenit.getLkm()); 
    treenit.lisaa(tre2); assertEquals("From: Treenit line: 55", 2, treenit.getLkm()); 
    treenit.lisaa(tre1); assertEquals("From: Treenit line: 56", 3, treenit.getLkm()); 
    assertEquals("From: Treenit line: 57", tre1, treenit.anna(0)); 
    assertEquals("From: Treenit line: 58", tre2, treenit.anna(1)); 
    assertEquals("From: Treenit line: 59", tre1, treenit.anna(2)); 
    assertEquals("From: Treenit line: 60", false, treenit.anna(1) == tre1); 
    assertEquals("From: Treenit line: 61", true, treenit.anna(1) == tre2); 
    try {
    assertEquals("From: Treenit line: 62", tre1, treenit.anna(3)); 
    fail("Treenit: 62 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    treenit.lisaa(tre1); assertEquals("From: Treenit line: 63", 4, treenit.getLkm()); 
    treenit.lisaa(tre1); assertEquals("From: Treenit line: 64", 5, treenit.getLkm()); 
    treenit.lisaa(tre1); treenit.lisaa(tre2); 
    treenit.lisaa(tre1); treenit.lisaa(tre2); 
    treenit.lisaa(tre1); treenit.lisaa(tre2); 
    treenit.lisaa(tre1); 
    assertEquals("From: Treenit line: 69", 12, treenit.getLkm()); 
    treenit.lisaa(tre1); 
    assertEquals("From: Treenit line: 71", 13, treenit.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKorvaaTaiLisaa87 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testKorvaaTaiLisaa87() throws CloneNotSupportedException {    // Treenit: 87
    Treenit treenit = new Treenit(); 
    Treeni tre1 = new Treeni(); 
    tre1.rekisteroi(); 
    tre1.taytaTreeni(); 
    treenit.lisaa(tre1); 
    Treeni tre2 = new Treeni(); 
    tre2.rekisteroi(); 
    tre2.taytaTreeni(); 
    treenit.lisaa(tre2); 
    treenit.korvaaTaiLisaa(tre1); 
    treenit.korvaaTaiLisaa(tre2); 
    assertEquals("From: Treenit line: 101", 2, treenit.getLkm()); 
    Treeni klooni = tre1.clone(); 
    assertEquals("From: Treenit line: 103", true, tre1.toString().equals(klooni.toString())); 
    treenit.korvaaTaiLisaa(klooni); 
    assertEquals("From: Treenit line: 105", 2, treenit.getLkm()); 
    tre1.parse("1|09.06.2023|kotikuntosali|60|5|-"); 
    assertEquals("From: Treenit line: 107", false, tre1.toString().equals(klooni.toString())); 
    treenit.korvaaTaiLisaa(tre1); 
    assertEquals("From: Treenit line: 109", 3, treenit.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnna131 
   * @throws SailoException when error
   */
  @Test
  public void testAnna131() throws SailoException {    // Treenit: 131
    Treenit treenit = new Treenit(); 
    Treeni tre1 = new Treeni(); 
    Treeni tre2 = new Treeni(); 
    assertEquals("From: Treenit line: 136", 0, treenit.getLkm()); 
    treenit.lisaa(tre1); assertEquals("From: Treenit line: 137", 1, treenit.getLkm()); 
    treenit.lisaa(tre2); assertEquals("From: Treenit line: 138", 2, treenit.getLkm()); 
    treenit.lisaa(tre1); assertEquals("From: Treenit line: 139", 3, treenit.getLkm()); 
    assertEquals("From: Treenit line: 140", tre1, treenit.anna(0)); 
    assertEquals("From: Treenit line: 141", tre2, treenit.anna(1)); 
    assertEquals("From: Treenit line: 142", tre1, treenit.anna(2)); 
    assertEquals("From: Treenit line: 143", false, treenit.anna(1) == tre1); 
    assertEquals("From: Treenit line: 144", true, treenit.anna(1) == tre2); 
    try {
    assertEquals("From: Treenit line: 145", tre1, treenit.anna(3)); 
    fail("Treenit: 145 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta160 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta160() throws SailoException {    // Treenit: 160
    Treenit treenit = new Treenit(); 
    Treeni tre1 = new Treeni(); tre1.taytaTreeni(); 
    Treeni tre2 = new Treeni(); tre2.taytaTreeni(); 
    Treeni tre3 = new Treeni(); tre3.taytaTreeni(); 
    Treeni tre4 = new Treeni(); tre4.taytaTreeni(); 
    Treeni tre5 = new Treeni(); tre5.taytaTreeni(); 
    String nimi = "testi"; 
    File tiedosto = new File(nimi + "/treenit.dat"); 
    File dir = new File(nimi); 
    dir.mkdir(); 
    tiedosto.delete(); 
    treenit.lisaa(tre1); 
    treenit.lisaa(tre2); 
    treenit.lisaa(tre3); 
    treenit.lisaa(tre4); 
    treenit.lisaa(tre5); 
    treenit.talleta(nimi); 
    Iterator<Treeni> i = treenit.iterator(); 
    assertEquals("From: Treenit line: 181", tre1.toString(), i.next().toString()); 
    assertEquals("From: Treenit line: 182", tre2.toString(), i.next().toString()); 
    assertEquals("From: Treenit line: 183", tre3.toString(), i.next().toString()); 
    assertEquals("From: Treenit line: 184", tre4.toString(), i.next().toString()); 
    assertEquals("From: Treenit line: 185", tre5.toString(), i.next().toString()); 
    treenit = new Treenit(); 
    i = treenit.iterator(); 
    assertEquals("From: Treenit line: 188", false, i.hasNext()); 
    treenit.lueTiedostosta(nimi); 
    treenit.lisaa(tre5); 
    treenit.talleta(nimi); 
    assertEquals("From: Treenit line: 192", true, tiedosto.delete()); 
    assertEquals("From: Treenit line: 193", true, dir.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi268 
   * @throws SailoException when error
   */
  @Test
  public void testEtsi268() throws SailoException {    // Treenit: 268
    Treenit treenit = new Treenit(); 
    Treeni treeni1 = new Treeni(); treeni1.parse("1|09.06.2023|kotikuntosali|60|5|-"); 
    Treeni treeni2 = new Treeni(); treeni2.parse("2|10.06.2023|ulkokuntosali|50|1|jatkossa juotavaa"); 
    Treeni treeni3 = new Treeni(); treeni3.parse("3|12.06.2023|kotikuntosali|70|3|lisää painoja"); 
    treenit.lisaa(treeni1); treenit.lisaa(treeni2); treenit.lisaa(treeni3); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTreenitIterator291 
   * @throws SailoException when error
   */
  @Test
  public void testTreenitIterator291() throws SailoException {    // Treenit: 291
    Treenit treenit = new Treenit(); 
    Treeni tre1 = new Treeni(), tre2 = new Treeni(); 
    tre1.rekisteroi(); tre2.rekisteroi(); 
    treenit.lisaa(tre1); 
    treenit.lisaa(tre2); 
    treenit.lisaa(tre1); 
    StringBuffer ids = new StringBuffer(30); 
    for (Treeni treeni:treenit) { // Kokeillaan for-silmukan toimintaa
    ids.append(" "+treeni.getTunnusNro()); 
    }
    String tulos = " " + tre1.getTunnusNro() + " " + tre2.getTunnusNro() + " " + tre1.getTunnusNro(); 
    assertEquals("From: Treenit line: 306", tulos, ids.toString()); 
    ids = new StringBuffer(30); 
    for (Iterator<Treeni>  i=treenit.iterator(); i.hasNext(); ) { // ja iteraattorin toimintaa
    Treeni treeni = i.next(); 
    ids.append(" "+treeni.getTunnusNro()); 
    }
    assertEquals("From: Treenit line: 312", tulos, ids.toString()); 
    Iterator<Treeni>  i=treenit.iterator(); 
    assertEquals("From: Treenit line: 314", true, i.next() == tre1); 
    assertEquals("From: Treenit line: 315", true, i.next() == tre2); 
    assertEquals("From: Treenit line: 316", true, i.next() == tre1); 
    try {
    i.next(); 
    fail("Treenit: 317 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}