package punttisalimuistio.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import punttisalimuistio.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.06.24 11:55:07 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TreeniTest {



  // Generated by ComTest BEGIN
  /** testGetTunnusNro44 */
  @Test
  public void testGetTunnusNro44() {    // Treeni: 44
    Treeni tre1 = new Treeni(); 
    assertEquals("From: Treeni line: 46", 0, tre1.getTunnusNro()); 
    tre1.rekisteroi(); 
    int n1 = tre1.getTunnusNro(); 
    assertEquals("From: Treeni line: 49", true, n1 > 0 && n1+1 == tre1.getSeuraavaNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetSeuraavaNro61 */
  @Test
  public void testGetSeuraavaNro61() {    // Treeni: 61
    Treeni tre1 = new Treeni(); 
    tre1.rekisteroi(); 
    assertEquals("From: Treeni line: 64", true, tre1.getSeuraavaNro() == 1 + tre1.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPvm76 */
  @Test
  public void testGetPvm76() {    // Treeni: 76
    Treeni tre1 = new Treeni(); 
    assertEquals("From: Treeni line: 78", "", tre1.getPvm()); 
    tre1.taytaTreeni(); 
    assertEquals("From: Treeni line: 80", "12.06.2023", tre1.getPvm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTaytaTreeni150 */
  @Test
  public void testTaytaTreeni150() {    // Treeni: 150
    Treeni tre1 = new Treeni(); 
    assertEquals("From: Treeni line: 152", "", tre1.getPvm()); 
    tre1.taytaTreeni(); 
    assertEquals("From: Treeni line: 154", "12.06.2023", tre1.getPvm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi193 */
  @Test
  public void testRekisteroi193() {    // Treeni: 193
    Treeni tre1 = new Treeni(); 
    assertEquals("From: Treeni line: 195", 0, tre1.getTunnusNro()); 
    tre1.rekisteroi(); 
    int n1 = tre1.getTunnusNro(); 
    assertEquals("From: Treeni line: 198", true, n1 > 0 && n1+1 == tre1.getSeuraavaNro()); 
    Treeni tre2 = new Treeni(); 
    assertEquals("From: Treeni line: 200", 0, tre2.getTunnusNro()); 
    tre2.rekisteroi(); 
    int n2 = tre2.getTunnusNro(); 
    assertEquals("From: Treeni line: 203", true, n2 > 0 && n2+1 == tre2.getSeuraavaNro()); 
    assertEquals("From: Treeni line: 204", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone218 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone218() throws CloneNotSupportedException {    // Treeni: 218
    Treeni tre = new Treeni(); 
    tre.parse("3|12.06.2023|kotikuntosali|70"); 
    Treeni klooni = tre.clone(); 
    assertEquals("From: Treeni line: 223", true, tre.toString().equals(klooni.toString())); 
    tre.parse("1|09.06.2023|kotikuntosali|60|5|-"); 
    assertEquals("From: Treeni line: 225", false, tre.toString().equals(klooni.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString238 */
  @Test
  public void testToString238() {    // Treeni: 238
    Treeni tre1 = new Treeni(); 
    tre1.parse("3|12.06.2023|kotikuntosali|70"); 
    assertEquals("From: Treeni line: 241", true, tre1.toString().startsWith("3|12.06.2023|kotikuntosali|70|"));  // on yli 4 kenttää, siksi loppuu tolppaan
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse261 */
  @Test
  public void testParse261() {    // Treeni: 261
    Treeni tre1 = new Treeni(); 
    tre1.parse("3 |12.06.2023|kotikuntosali|70"); 
    assertEquals("From: Treeni line: 264", 3, tre1.getTunnusNro()); 
    assertEquals("From: Treeni line: 265", "12.06.2023", tre1.getPvm()); 
    assertEquals("From: Treeni line: 266", true, tre1.toString().startsWith("3|12.06.2023|kotikuntosali|70|"));  // on yli 4 kenttää, siksi loppu |
    tre1.rekisteroi(); 
    int n = tre1.getTunnusNro(); 
    tre1.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    tre1.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Treeni line: 271", n+20+1, tre1.getTunnusNro()); 
  } // Generated by ComTest END
}