package punttisalimuistio.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import punttisalimuistio.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.06.19 23:37:06 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TreeniTest {



  // Generated by ComTest BEGIN
  /** testGetTunnusNro42 */
  @Test
  public void testGetTunnusNro42() {    // Treeni: 42
    Treeni tre1 = new Treeni(); 
    assertEquals("From: Treeni line: 44", 0, tre1.getTunnusNro()); 
    tre1.rekisteroi(); 
    int n1 = tre1.getTunnusNro(); 
    assertEquals("From: Treeni line: 47", true, n1 > 0 && n1+1 == tre1.getSeuraavaNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetSeuraavaNro59 */
  @Test
  public void testGetSeuraavaNro59() {    // Treeni: 59
    Treeni tre1 = new Treeni(); 
    tre1.rekisteroi(); 
    assertEquals("From: Treeni line: 62", true, tre1.getSeuraavaNro() == 1 + tre1.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPvm74 */
  @Test
  public void testGetPvm74() {    // Treeni: 74
    Treeni tre1 = new Treeni(); 
    assertEquals("From: Treeni line: 76", "", tre1.getPvm()); 
    tre1.taytaTreeni(); 
    assertEquals("From: Treeni line: 78", "12.06.2023", tre1.getPvm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTaytaTreeni102 */
  @Test
  public void testTaytaTreeni102() {    // Treeni: 102
    Treeni tre1 = new Treeni(); 
    assertEquals("From: Treeni line: 104", "", tre1.getPvm()); 
    tre1.taytaTreeni(); 
    assertEquals("From: Treeni line: 106", "12.06.2023", tre1.getPvm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi145 */
  @Test
  public void testRekisteroi145() {    // Treeni: 145
    Treeni tre1 = new Treeni(); 
    assertEquals("From: Treeni line: 147", 0, tre1.getTunnusNro()); 
    tre1.rekisteroi(); 
    int n1 = tre1.getTunnusNro(); 
    assertEquals("From: Treeni line: 150", true, n1 > 0 && n1+1 == tre1.getSeuraavaNro()); 
    Treeni tre2 = new Treeni(); 
    assertEquals("From: Treeni line: 152", 0, tre2.getTunnusNro()); 
    tre2.rekisteroi(); 
    int n2 = tre2.getTunnusNro(); 
    assertEquals("From: Treeni line: 155", true, n2 > 0 && n2+1 == tre2.getSeuraavaNro()); 
    assertEquals("From: Treeni line: 156", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString170 */
  @Test
  public void testToString170() {    // Treeni: 170
    Treeni tre1 = new Treeni(); 
    tre1.parse("3|12.06.2023|kotikuntosali|70"); 
    assertEquals("From: Treeni line: 173", true, tre1.toString().startsWith("3|12.06.2023|kotikuntosali|70|"));  // on yli 4 kenttää, siksi loppuu tolppaan
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse193 */
  @Test
  public void testParse193() {    // Treeni: 193
    Treeni tre1 = new Treeni(); 
    tre1.parse("3 |12.06.2023|kotikuntosali|70"); 
    assertEquals("From: Treeni line: 196", 3, tre1.getTunnusNro()); 
    assertEquals("From: Treeni line: 197", "12.06.2023", tre1.getPvm()); 
    assertEquals("From: Treeni line: 198", true, tre1.toString().startsWith("3|12.06.2023|kotikuntosali|70|"));  // on yli 4 kenttää, siksi loppu |
    tre1.rekisteroi(); 
    int n = tre1.getTunnusNro(); 
    tre1.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    tre1.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Treeni line: 203", n+20+1, tre1.getTunnusNro()); 
  } // Generated by ComTest END
}